apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boxfuse
  labels:
    app: boxfuse
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: boxfuse
    spec:
      containers:
      - image: 
        name: gcr.io/hello-world-241305/image-repo:boxfuse
        ports:
        - containerPort: 8080
